#!/usr/bin/env python3
"""Plot recall-vs-QPS curves and write markdown result tables.

Reads the compare.py CSVs in one machine's results directory
(bench/results/<machine>/, one CSV per dataset) and writes there
  <dataset>.png   recall@10 (x) vs QPS (log y), single + batch
  summary.md      QPS at recall targets (interpolated), build metrics
Also renders ablation.csv / scaling.csv (from bench_main) into markdown if present.
"""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from results_common import REPO, fnum, qps_at_recall, read_csv, read_env  # noqa: E402
# Categorical slots in fixed order: identity follows the library, never its rank.
COLORS = {"engine": "#2a78d6", "hnswlib": "#eb6834", "faiss": "#1baf7a"}
MARKERS = {"engine": "o", "hnswlib": "s", "faiss": "^"}
NAMES = {"engine": "hnsw-engine (this)", "hnswlib": "hnswlib", "faiss": "FAISS HNSWFlat"}
INK, INK2, GRID, SURFACE = "#0b0b0b", "#52514e", "#e4e3df", "#fcfcfb"
THRESHOLDS = (0.90, 0.95, 0.99)


def plot_dataset(rows: list[dict], out: Path, title: str) -> None:
    modes = [m for m in ("single", "batch") if any(r["mode"] == m for r in rows)]
    fig, axes = plt.subplots(1, len(modes), figsize=(6.2 * len(modes), 4.6), facecolor=SURFACE, squeeze=False)
    for ax, mode in zip(axes[0], modes):
        ax.set_facecolor(SURFACE)
        threads = next(r["threads"] for r in rows if r["mode"] == mode)
        for lib in COLORS:
            pts = sorted((fnum(r["recall"]), fnum(r["qps"])) for r in rows if r["library"] == lib and r["mode"] == mode)
            if not pts:
                continue
            xs, ys = zip(*pts)
            ax.plot(xs, ys, color=COLORS[lib], lw=2, marker=MARKERS[lib], ms=6, mec=SURFACE, mew=1.5,
                    label=NAMES[lib])
        ax.set_yscale("log")
        ax.set_xlabel("Recall@10", color=INK2)
        ax.set_ylabel("Queries per second (log)", color=INK2)
        sub = "1 thread, one query per call" if mode == "single" else f"batched, {threads} threads"
        ax.set_title(f"{title} — {sub}", color=INK, fontsize=11, loc="left")
        ax.grid(True, which="major", color=GRID, lw=0.8)
        ax.grid(True, which="minor", axis="y", color=GRID, lw=0.4, alpha=0.6)
        for s in ("top", "right"):
            ax.spines[s].set_visible(False)
        for s in ("left", "bottom"):
            ax.spines[s].set_color(GRID)
        ax.tick_params(colors=INK2)
        ax.legend(frameon=False, labelcolor=INK, loc="lower left")
    fig.tight_layout()
    fig.savefig(out, dpi=140, facecolor=SURFACE)
    plt.close(fig)


def rss_growth(r: dict, env: dict) -> str:
    """macOS runs before compare.py measured current RSS via `ps` recorded peak
    RSS instead, which makes the growth column meaningless."""
    v = fnum(r["rss_delta_mb"])
    valid = not env.get("os", "").startswith("Darwin") or env.get("rss_growth") == "ps"
    return "—" if math.isnan(v) or not valid else f"{v:.0f}"


def fmt(v: float, nd: int = 0) -> str:
    return "—" if math.isnan(v) else f"{v:,.{nd}f}"


def summary_md(per_dataset: dict[str, list[dict]], env: dict) -> str:
    out = ["# Benchmark summary (generated by bench/python/plot.py)", ""]
    for name, rows in per_dataset.items():
        r0 = rows[0]
        out += [f"## {name}", "",
                f"n={r0['n']}, dim={r0['dim']}, metric={r0['metric']}, M={r0['M']}, "
                f"ef_construction={r0['efc']}, k={r0['k']}, threads={r0['threads']}", ""]
        libs = [lib for lib in COLORS if any(r["library"] == lib for r in rows)]
        for mode in ("single", "batch"):
            if not any(r["mode"] == mode for r in rows):
                continue
            label = "single-thread, one query per call" if mode == "single" else "batched, multi-thread"
            out += [f"**QPS at recall@10 target ({label}; interpolated on the recall-QPS curve)**", "",
                    "| library | " + " | ".join(f"{t:.2f}" for t in THRESHOLDS) + " |",
                    "|---|" + "---:|" * len(THRESHOLDS)]
            for lib in libs:
                out.append(f"| {NAMES[lib]} | " + " | ".join(fmt(qps_at_recall(rows, lib, mode, t)) for t in THRESHOLDS) + " |")
            out.append("")
        out += ["**Recall / QPS / latency per ef (single-thread)**", "",
                "| library | ef | recall@10 | QPS | p50 µs | p99 µs |", "|---|---:|---:|---:|---:|---:|"]
        for lib in libs:
            for r in rows:
                if r["library"] == lib and r["mode"] == "single":
                    out.append(f"| {NAMES[lib]} | {r['ef']} | {fnum(r['recall']):.4f} | {fmt(fnum(r['qps']))} | "
                               f"{fmt(fnum(r['p50_us']))} | {fmt(fnum(r['p99_us']))} |")
        out += ["", "**Build**", "",
                "| library | version | build s (N threads) | build s (1 thread) | index file MB | RSS growth MB | peak RSS MB |",
                "|---|---|---:|---:|---:|---:|---:|"]
        for lib in libs:
            r = next(x for x in rows if x["library"] == lib)
            out.append(f"| {NAMES[lib]} | {r['version']} | {fnum(r['build_s']):.1f} | {fmt(fnum(r['build_1t_s']), 1)} | "
                       f"{fnum(r['index_bytes']) / 2**20:.0f} | {rss_growth(r, env)} | "
                       f"{max(fnum(x['peak_rss_mb']) for x in rows if x['library'] == lib):.0f} |")
        out.append("")
    return "\n".join(out)


def bench_main_md(path: Path, title: str, cols: list[str]) -> str:
    rows = read_csv(path)
    out = [f"## {title}", "", "| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for r in rows:
        out.append("| " + " | ".join(r.get(c, "") for c in cols) + " |")
    return "\n".join(out) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--results", required=True, help="one machine's directory, e.g. bench/results/apple-m5")
    args = p.parse_args()
    res = Path(args.results)
    per_dataset: dict[str, list[dict]] = defaultdict(list)
    # Use the real ann-benchmarks results when present, else the synthetic ones;
    # re-check runs are supplementary and not datasets of their own.
    real = all((res / f"{d}.csv").exists() for d in ("sift", "glove", "gist"))
    for f in sorted(res.glob("*.csv")):
        if f.stem.startswith("recheck_") or (real and f.stem.startswith("synth-")):
            continue
        rows = read_csv(f)
        if rows and "library" in rows[0]:
            per_dataset[f.stem] = rows
            plot_dataset(rows, res / f"{f.stem}.png", rows[0]["dataset"])
            print(f"wrote {res / (f.stem + '.png')}")
    md = summary_md(per_dataset, read_env(res))
    cols = ["label", "isa", "prefetch", "search_threads", "ef", "recall", "qps", "p50_us", "p99_us"]
    if (res / "ablation.csv").exists():
        md += "\n" + bench_main_md(res / "ablation.csv", "Ablation (bench_main, engine only)", cols)
    if (res / "scaling.csv").exists():
        md += "\n" + bench_main_md(res / "scaling.csv", "Build thread scaling (bench_main, engine only)",
                                   ["build_threads", "n", "build_s", "ef", "recall"])
    (res / "summary.md").write_text(md)
    print(f"wrote {res / 'summary.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
